### ISSUE TITLE
[GH Request] Onboard John Swope jswope00

### ISSUE THREAD

**Issue by jswope00** [openedx/axim-engineering#972] opened 2023-11-09 19:47 UTC
### Firm Name

curricu.me

### User List (case sensitive!) - Please also include in ticket title

Requesting CC access for John Swope with gh username jswope00 to repos:
https://github.com/openedx/edx-documentation
https://github.com/openedx/docs.openedx.org
https://github.com/openedx/openedx-demo-course
https://github.com/openedx/openedx-demo-course-new

Reason: [<link to nomination thread>](https://discuss.openedx.org/t/core-contributor-nomination-john-swope/11514)

Instructions: Please give access to the repos listed above. 

Thank you!

### Start Date

9 November 2023

### Urgency

Low (2 weeks)

**Comment by sarina** [comment] 2023-11-09 21:53
Dupe of #971

**Closed by sarina** 2023-11-09 21:53 UTC
Labels: github-request
