### ISSUE TITLE
[GH Request] Onboard <ADD USERNAMES HERE>

### ISSUE THREAD

**Issue by HacDmv** [openedx/axim-engineering#712] opened 2023-03-31 18:37 UTC
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Emily Aquin, @emrosarioa, eaquin@2u.com

### Start Date

04/03/23

### Urgency

High (< 3 days)

**Comment by sarina** [comment] 2023-04-04 14:30
@georgebabey is @HacDmv authorized on behalf of 2U to issue onboarding requests?

**Comment by brian-smith-tcril** [comment] 2023-04-04 14:33
closing as a dupe of https://github.com/openedx/axim-engineering/issues/708

**Closed by brian-smith-tcril** 2023-04-04 14:33 UTC
Labels: github-request
