### ISSUE TITLE
[GH Request] Onboard tasneem-titus

### ISSUE THREAD

**Issue by mmnxumalo** [openedx/axim-engineering#792] opened 2023-06-19 10:07 UTC
### Firm Name

EdX & Getsmarter

### User List (case sensitive!) - Please also include in ticket title

Tasneem Titus,tasneem-titus

### Start Date

19 June 2023

### Urgency

High (< 3 days)

### Special Requests

push-pull-all

**Comment by brian-smith-tcril** [comment] 2023-06-20 15:27
@mmnxumalo I don't see a record for you in salesforce. @georgebabey is this request approved?

**Comment by mmnxumalo** [comment] 2023-06-28 10:18
@brian-smith-tcril  this request is for @tasneem-titus and there's a case on salesforce

**Comment by georgebabey** [comment] 2023-06-29 14:16
This is approved, but is a dupe of https://github.com/openedx/axim-engineering/issues/805

**Comment by brian-smith-tcril** [comment] 2023-06-29 21:02
Added to CLA database. Invited to the Open edX GitHub org, as well as the `openedx-triage` and `push-pull-all` teams.

**Closed by brian-smith-tcril** 2023-06-29 21:02 UTC
Labels: github-request
