### ISSUE TITLE
[GH Request] Onboard jawad-khan

### ISSUE THREAD

**Issue by iobrien2u** [openedx/axim-engineering#1001] opened 2023-12-15 17:18 UTC
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Jawad Khan, jawad-khan

### Start Date

5 October 2022

### Urgency

High (< 3 days)

### Special Requests

Hello, 

We received a ticket on Helpdesk from Jawad Khan stating that their openedx GitHub access was revoked. We are showing access tracked on our end since October 5th 2022 so we are unsure if this was done in error. Please see Jawad's included business context below:

"I have been adding my contributions on behalf of the edx-mobile team in the
edx-platform repository, but suddenly I got permission errors locally.
When I looked on github it said my user doesn't have access anymore. I am
working on this ticket
<https://2u-internal.atlassian.net/browse/LEARNER-9754> to create sandbox
with some changes on lms."

Let me know if additional information is needed!

Ian O'Brien
IT Helpdesk

**Comment by miankhalid** [comment] 2023-12-19 04:59
any update on this @openedx/axim-oncall?

**Comment by sarina** [comment] 2023-12-19 16:41
I don't see any change in this user's membership. Perhaps they need to set up their local access token properly? https://github.com/orgs/openedx/people?query=jawad

**Comment by jawad-khan** [comment] 2023-12-20 14:18
@sarina I don't think its related to local access token.I confirmed it by attempting to edit a file on github repo(screenshot attached).

<img width="1116" alt="Screenshot 2023-12-20 at 7 14 31 PM" src="https://github.com/openedx/axim-engineering/assets/5320368/299bfae2-fccd-44cc-a12d-6c14a80d36a1">

**Comment by sarina** [comment] 2023-12-20 16:59
This seems to be related to the recent work @nedbat did on teams - I'm asking him to weigh in on the best path forward.

**Comment by sarina** [comment] 2023-12-20 17:40
@jawad-khan ok, thank you for your patience, I had to figure out what was going on with your access. Can you check now, and close this ticket if your access issues are resolved?

**Comment by jawad-khan** [comment] 2023-12-21 07:42
@sarina I am still having the same issue, unable to edit any file on github repo.

**Comment by sarina** [comment] 2023-12-21 19:03
@jawad-khan I am so sorry I think I didn't save the page. It looks like you should have access now:

<img width="1274" alt="image" src="https://github.com/openedx/axim-engineering/assets/1985317/86126b56-c2d0-45c2-a557-1cb62840f20a">

**Comment by feanil** [comment] 2024-01-03 14:37
@jawad-khan can you confirm that you have access, it looks like you do from my perspective.
![image](https://github.com/openedx/axim-engineering/assets/781561/2f4040e9-6589-4e03-8537-abfc86e7cb69)

**Comment by feanil** [comment] 2024-01-08 15:24
I think this should be resolved and haven't heard back from the person impacted so I'm closing this for now, feel free to re-open, comment here or make a new issue if this is still an issue.

**Closed by feanil** 2024-01-08 15:24 UTC
Labels: github-request
