### ISSUE TITLE
Develop a plug-in system that closes the gaps where the custom theming system does not cover the extent of comprehensive theming flexibility

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/axim-engineering#419] opened 2022-08-15 17:11 UTC
### Problem

The MFE theming and branding methods are not compatible with comprehensive theming. “It was something that we all kind of agreed on and now we are completely ignoring it.” This has a direct and negative impact on provider clients, as each customer may require different branding and modifications.

### Product/Platform Value

Allowing for simple across-the-board theming and extensibility has a direct impact on adoption: the easier it is to do, the more users the platform will have.

### Contingencies

Must complete https://github.com/openedx/tcril-engineering/issues/418 first.

**Comment by brian-smith-tcril** [comment] 2022-10-17 15:06
It's not clear to me how this differs from https://github.com/openedx/tcril-engineering/issues/430 and https://github.com/openedx/tcril-engineering/issues/429

**Comment by arbrandes** [comment] 2022-10-17 18:35
@brian-smith-tcril, yeah, there's significant overlap.  For now, if you're interested in reading up on the main ideas for plugins, I would look at the "Related or in-progress work" in #429.

**Comment by arbrandes** [comment] 2023-10-05 17:03
Another duplicate of https://github.com/openedx/platform-roadmap/issues/27.  The original intention was to have a more engineering facing ticket, in contrast to the product-facing roadmap one, but we opened the engineering tickets prematurely: we have yet to define what we should actually do, and are holding a summit at the end of the month to do so.

**Closed by arbrandes** 2023-10-05 17:03 UTC
Labels: epic
